from pathlib import Path
root=Path(__file__).resolve().parents[1]
main=(root/'app/src/main/java/com/xingyu/music/MainActivity.java').read_text(encoding='utf-8')
ui=(root/'app/src/main/java/com/xingyu/music/ui/Ui.java').read_text(encoding='utf-8')
appearance=(root/'app/src/main/java/com/xingyu/music/ui/AppearanceSystem.java').read_text(encoding='utf-8')
motion=(root/'app/src/main/java/com/xingyu/music/ui/SpringMotion.java').read_text(encoding='utf-8')
star2=(root/'app/src/main/java/com/xingyu/music/ui/StarfieldView.java').read_text(encoding='utf-8')
star3=(root/'app/src/main/java/com/xingyu/music/ui/Starfield3DView.java').read_text(encoding='utf-8')
vinyl=(root/'app/src/main/java/com/xingyu/music/ui/VinylRecordView.java').read_text(encoding='utf-8')
halo=(root/'app/src/main/java/com/xingyu/music/ui/FluidTrackHaloDrawable.java').read_text(encoding='utf-8')
recommendation=(root/'app/src/main/java/com/xingyu/music/ui/RecommendationGlassDrawable.java').read_text(encoding='utf-8')
icons=(root/'app/src/main/java/com/xingyu/music/ui/IconView.java').read_text(encoding='utf-8')
vinyl_stack=(root/'app/src/main/java/com/xingyu/music/ui/VinylStackView.java').read_text(encoding='utf-8')
ringtone=(root/'app/src/main/java/com/xingyu/music/ui/RingtoneLyricSelectorView.java').read_text(encoding='utf-8')
checks=[]
def check(cond,msg):
    if not cond: raise AssertionError(msg)
    checks.append(msg)
for token in ['MODE_SYSTEM','MODE_DEEP','MODE_OLED','MODE_MOONLIGHT','KEY_REDUCE_MOTION','KEY_REDUCE_TRANSPARENCY']:
    check(token in appearance, f'appearance token {token}')
check('private static int selectedMode = MODE_DEEP;' in appearance and 'p.getInt(KEY_MODE, MODE_DEEP)' in appearance, 'existing users preserve Deep appearance by default')
for token in ['contentSurface','functionalGlass','transientGlass','applyAppearance']:
    check(token in ui, f'material/palette primitive {token}')
for token in ['selectionDuration','pageDuration','sheetDuration','themeRevealDuration']:
    check(token in motion, f'semantic motion token {token}')
check('navSelectionPill' in main and 'animateNavSelectionPill' in main, 'persistent moving tab selection carrier')
check('installNavPressFeedback' in main and 'MotionEvent.ACTION_DOWN' in main, 'tabs acknowledge touch-down immediately')
check('switchRootTab' in main and 'rememberRootTabContext()' in main, 'tab switch saves prior context')
check('rootTabScrollY' in main and 'restoreRootTabContext' in main, 'root tab scroll context restoration')
check('rootTabOpenPlaylist' in main and 'rootTabSmartCollection' in main and 'rootTabSearchAllResultsOpen' in main, 'root tabs preserve nested destinations')
check('activeSearchAllList' in main and 'setSelectionFromTop' in main, 'search-all list position is restored across tab switches')
check('while (pageHost.getChildCount() > 1)' in main and 'outgoing.animate().cancel()' in main, 'interrupted tab navigation retargets current presentation')
check('startRootTabPhysics(outgoing, page, direction, width)' in main and 'incoming.setTranslationX(position[0])' in main and 'outgoing.setTranslationX(position[0] - direction * safeWidth)' in main, 'lateral tabs expose one-viewport transition process without overlap')
check('final boolean lateral = tab != previousTab' in main and 'final boolean push = !lateral' in main, 'cross-tab motion stays lateral even when restoring nested context')
check('navHost.setAlpha(1f - .54f * baseFade)' in main and 'navHost.setVisibility(View.GONE)' in main, 'new navigation layer participates in player morph')
check('showAppearanceSheet()' in main and 'ThemeRevealOverlay' in main, 'appearance control plus source-origin reveal')
check('rebuildHiddenPlayerForAppearance()' in main and 'buildNowPlaying();' in main, 'hidden Full Player rebinds local theme materials after appearance changes')
check('SpringMotion.isReducedMotion()' in main and 'reduceTransparency()' in main, 'accessibility fallbacks wired into UI')
check('!SpringMotion.isReducedMotion()' in star2 and '!SpringMotion.isReducedMotion()' in star3, 'starfield continuous motion respects reduced motion')
check('!SpringMotion.isReducedMotion()' in vinyl, 'vinyl decorative rotation respects reduced motion')
check('SpringMotion.isReducedMotion() ? 0.12f' in halo and 'needsAmbientMotion' in halo, 'album-reactive halo freezes ambient travel under reduced motion')
check('!SpringMotion.isReducedMotion()' in recommendation and 'if (SpringMotion.isReducedMotion()) return .42f' in recommendation, 'recommendation material animation has reduced-motion static frame')
check('SpringMotion.isReducedMotion() ? SpringMotion.selectionDuration()' in icons, 'icon morphs use reduced-motion duration')
check('SpringMotion.isReducedMotion() ? 110L : 240L' in vinyl_stack and 'Math.min(110L, duration)' in vinyl_stack, 'vinyl expand/settle motion shortens under reduced motion')
check('SpringMotion.isReducedMotion() ? 70L : 135L' in ringtone, 'ringtone lyric boundary motion shortens under reduced motion')
check('Ui.isLightAppearance()' in star3, '3D starfield remains legible in Moonlight')
check('Ui.functionalGlass(21, this)' in main and 'Ui.transientGlass(25, this)' in main, 'functional/transient material hierarchy used in shell')
print(f'PASS: {len(checks)} V92.9.0 visual-system policy checks')
