from pathlib import Path
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
manifest = root/'app/src/main/AndroidManifest.xml'
main = (root/'app/src/main/java/com/xingyu/music/MainActivity.java').read_text(encoding='utf-8')
service = (root/'app/src/main/java/com/xingyu/music/voice/VoiceAssistantService.java').read_text(encoding='utf-8')
parser = (root/'app/src/main/java/com/xingyu/music/voice/VoiceCommandParser.java').read_text(encoding='utf-8')
contract = (root/'app/src/main/java/com/xingyu/music/voice/VoiceAssistantContract.java').read_text(encoding='utf-8')
orb = (root/'app/src/main/java/com/xingyu/music/ui/VoiceOrbView.java').read_text(encoding='utf-8')
panel = (root/'app/src/main/java/com/xingyu/music/ui/VoiceAssistantPanel.java').read_text(encoding='utf-8')
checks=[]
def check(cond,msg):
    if not cond: raise AssertionError(msg)
    checks.append(msg)

ET.parse(manifest)
xml = manifest.read_text(encoding='utf-8')
check('android.permission.RECORD_AUDIO' in xml, 'record audio permission')
check('android.permission.FOREGROUND_SERVICE_MICROPHONE' in xml, 'microphone FGS permission')
check('android:foregroundServiceType="microphone"' in xml, 'microphone service type')
check('android.speech.RecognitionService' in xml, 'Android 11 speech service package visibility query')
check('VoiceAssistantService' in xml, 'voice service registered')
check('MODE_AUTO = "auto"' in contract and 'MODE_LOCAL = "local"' in contract and 'MODE_SYSTEM = "system"' in contract, 'three recognition modes')
check('KEY_RECOGNITION_MODE' in contract and 'recognitionModeLabel' in contract, 'recognition mode persisted and labeled')
check('createOnDeviceSpeechRecognizer' in service and 'createSpeechRecognizer(this)' in service, 'local and system recognizers both available')
check('else createRecognizer(canTryOnDeviceRecognizer())' not in service, 'V92.8.13 blind strategy removed')
check('localFirst = canTryOnDeviceRecognizer()' in service, 'auto mode is local-first')
check('automaticFallbackAllowed()' in service, 'fallback is restricted to auto mode')
check('EXTRA_PREFER_OFFLINE' in service and 'isLocalOnlyMode' in service, 'local-only asks recognizer to prefer offline')
check('triggerModelDownload' in service, 'missing local language model can request preparation')
check('ERROR_LANGUAGE_NOT_SUPPORTED' in service and 'ERROR_LANGUAGE_UNAVAILABLE' in service, 'language model failures are handled')
check('系统语音服务连接失败' in service and '当前网络不可用' in service and '本地优先' in service, 'network failures distinguish provider failure from device connectivity and point to local mode')
check('recognitionPaused' in service and 'recognizer.cancel()' in service, 'duplicate-final suppression and recognizer cancellation')
check('ERROR_AUDIO' in service and '麦克风暂不可用' in service, 'audio capture failure is visible')
check('recognizerReadyWatchdog' in service and '3800L' in service and '5200L' in service, 'recognizer ready watchdog allows OEM startup latency')
check('已连接 · ' in service and 'currentEngineLabel()' in service and 'onReadyForSpeech' in service, 'ready state names active engine')
check('听到了 · 继续说' in service and '正在识别…' in service, 'real speech phase feedback')
check('maybeUpdateNotification()' in service and 'lastNotificationSignature' in service, 'RMS notification throttling')
check('ERROR_TOO_MANY_REQUESTS' in service and '8_000L' in service, 'recognizer rate-limit backoff')
check('立即聆听' in service, 'notification direct-listen action')
check('EXTRA_OPEN_VOICE_SETTINGS' in service and '语音设置' in service, 'error overlay can open voice settings')
check('setLayerType(LAYER_TYPE_SOFTWARE' not in orb, 'voice orb does not force software rendering')
check('ValueAnimator.areAnimatorsEnabled()' in orb, 'reduced motion / animator scale respected')
check('VoiceGlassDrawable' in panel and 'VoiceOrbView' in panel, 'fluid glass voice panel composition')
check('showVoiceAssistantSettings()' in main and 'startVoiceAssistant(true)' in main, 'voice settings and direct-listen entry')
check('requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO}' in main, 'runtime microphone permission flow')
check('voiceModeButton("本地优先"' in main and 'voiceModeButton("仅本地"' in main and 'voiceModeButton("系统识别"' in main, 'settings expose three large recognition modes')
check('requestVoiceOfflineModel()' in main and 'triggerModelDownload' in main, 'settings can request offline Chinese model')
check('为什么有时需要联网？' in main, 'settings explain network use without permanent wall of text')
check('ACTION_MANAGE_OVERLAY_PERMISSION' in main, 'optional background overlay permission flow')
check('getBoolean(KEY_OVERLAY, false)' in contract, 'background overlay is opt-in')
check('PLAYLIST = Pattern.compile' in parser and 'SEARCH_ARTIST = Pattern.compile' in parser and 'PLAY_ARTIST = Pattern.compile' in parser, 'playlist/search/artist command parser retained')
print(f'PASS: {len(checks)} Lunaxy Voice policy checks')
